export const INCREMENT_REQUEST_COUNT = "INCREMENT_REQUEST_COUNT";
export const REDUCE_REQUEST_COUNT = "REDUCE_REQUEST_COUNT";
export const UPDATE_APP_MESSAGE = "UPDATE_APP_MESSAGE";
export const SET_WX_SHARE_CONFIG = "SET_WX_SHARE_CONFIG";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const SET_USER_LOGIN_STATE = "SET_USER_LOGIN_STATE";
export const UPDATE_STUDENT_INFO = "UPDATE_STUDENT_INFO";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const APP_ERROR_MESSAGE_STATUS = "UPDATE_APP_MESSAGE_STATUS";

