export const INCREMENT_REQUEST_COUNT = "INCREMENT_REQUEST_COUNT";
export const REDUCE_REQUEST_COUNT = "REDUCE_REQUEST_COUNT";
export const UPDATE_APP_ERROR_MESSAGE = "UPDATE_APP_ERROR_MESSAGE";
export const SET_WX_SHARE_CONFIG = "SET_WX_SHARE_CONFIG"

